apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-app
  labels:
    app: cast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
      - name: cast-container
        image: sikam90/cast-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

