apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service-container
        image: your-docker-registry/cast-service:latest
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service-container
        image: your-docker-registry/movie-service:latest
        ports:
        - containerPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sikam90
  labels:
    app: sikam90
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sikam90
  template:
    metadata:
      labels:
        app: sikam90
    spec:
      containers:
      - name: sikam90-container
        image: your-docker-registry/sikam90:latest
        ports:
        - containerPort: 8082
