apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  labels:
    app: movie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie-container
        image: sikam90/movie-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
