apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  namespace: dev
  labels:
    app: movie-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: sikam/jenkins-devops-exam:movie-service
        ports:
        - containerPort: 80

