services:
  movie-service:
    build: ./movie-service
    ports:
      - "8081:8080"

  cast-service:
    build: ./cast-service
    ports:
      - "8082:8080"

  nginx:
    build: ./nginx
    ports:
      - "8085:80"
